site_name: Unknown Forge
site_url: https://torfmuer.github.io/Unknown-Forge/
nav:
  - Home: index.md
  - Rifle Builder: rb.md
theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: amber
plugins:
  - search

